#sdk: "/usr/local/rvm/gems/ruby-1.9.2-p290/gems/rhodes-4.0.0.beta.41"
#sdk: ../../rhodes
sdkversion: 4.0.0
name: simplescan
version: 1.0
vendor: rhomobile
build: debug
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.simplescan
  BundleURLScheme: simplescan
wp:
  productid: '26cbdad0-17c3-0131-bfa5-3c075409010c'
symbian:
  uid: '0xee880cfe'
android:
  version: 2.1

app_type: "rhoelements"
javascript_application: true
minify:
  js: false
  css: false

motorola_license_company: "SPB Testing"
motorola_license: "700A616A081D151A000307711A7E1C75"
